parameters:
  "service-dir":
    default: "sdk/openai"
  "dependencies":
    default: ""
emit:
 - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/../"
    output-file: "{azure-resource-provider-folder}/AzureOpenAI/inference/{version-status}/{version}/generated.json"
    azure-resource-provider-folder: "data-plane"
    examples-directory: examples
    omit-unreachable-types: true
  "@azure-tools/typespec-python":
    package-mode: "azure-dataplane"
    package-dir: "azure-openai"
    package-name: "azure-openai"